#[allow(dead_code)]
[package]
name = "raytracer"
version = "0.1.0"
authors = ["Sander Verbeek <sanderman@gmail.com>"]
edition = "2018"

[dependencies]
image   = "0.21.1"
nalgebra-glm = "0.4.0"
rand = "0.6"